// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZVam336xcrY4CRlnClTM6DGqp_c94RLQ',
    appId: '1:943694273271:web:338da244298897c6ea91f2',
    messagingSenderId: '943694273271',
    projectId: 'team-roping-event-app',
    authDomain: 'team-roping-event-app.firebaseapp.com',
    storageBucket: 'team-roping-event-app.appspot.com',
    measurementId: 'G-KB57WB7NCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFNFKtXiv2V17dxudWgoMaSbbN8qwHbZc',
    appId: '1:943694273271:android:153ab6eb80caa5d5ea91f2',
    messagingSenderId: '943694273271',
    projectId: 'team-roping-event-app',
    storageBucket: 'team-roping-event-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzP5Nz8FaFr96qsHt7A9Sv8QKOUcRs3MU',
    appId: '1:943694273271:ios:6e12109c68eb52f9ea91f2',
    messagingSenderId: '943694273271',
    projectId: 'team-roping-event-app',
    storageBucket: 'team-roping-event-app.appspot.com',
    iosBundleId: 'com.haskell.ropingEventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzP5Nz8FaFr96qsHt7A9Sv8QKOUcRs3MU',
    appId: '1:943694273271:ios:8d3d78dc1e8715b5ea91f2',
    messagingSenderId: '943694273271',
    projectId: 'team-roping-event-app',
    storageBucket: 'team-roping-event-app.appspot.com',
    iosBundleId: 'com.haskell.ropingEventApp.RunnerTests',
  );
}
